language: r
cache: packages
r_check_args: --as-cran

r:
  - release
  - devel

os:
  - windows
  - linux

matrix:
  fast_finish: true
  allow_failures:
  - r: devel

notifications:
  email:
    on_success: change
    on_failure: change
