language: r
cache: packages
r_check_args: --as-cran

r:
  - release
  - devel
  - 3.4
  - 3.3
  - 3.2
  - 3.1
  - 3.0

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: devel
    - r: 3.1
    - r: 3.0

notifications:
  email:
    on_success: change
    on_failure: change
